version: "3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=remo
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Contrasena1!
    ports:
    - 5432:5432

  remo_app:
    build: .
    volumes:
      - static:/code/static
      - .:/code
    depends_on:
      - db
  
  nginx:
    image: nginx:1.13
    ports:
      - 8100:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static:/code/static
    depends_on:
      - remo_app

volumes:
  .:
  static: